# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-01 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='client_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='contact_number',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='contact_person',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='proj_name',
            new_name='project_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='clients',
        ),
        migrations.AddField(
            model_name='client',
            name='projects',
            field=models.ManyToManyField(to='crm_app.Project'),
        ),
    ]
