# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-01 23:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0002_auto_20180201_2324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='number',
            new_name='contact_number',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='person',
            new_name='contact_person',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_name',
            new_name='name',
        ),
    ]
