# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-02 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0003_auto_20180201_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='contact_number',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact_person',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
