# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-03 06:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0004_auto_20180202_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='projects',
        ),
        migrations.AddField(
            model_name='project',
            name='assigned_to',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='crm_app.Client'),
            preserve_default=False,
        ),
    ]
