# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-04 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0006_auto_20180204_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Complete')]),
        ),
    ]
